# Generated by Django 4.2 on 2023-04-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('emp_name', models.CharField(max_length=75)),
                ('emp_address', models.CharField(max_length=25)),
            ],
        ),
    ]
